In [1]:
# Python code for Max Pooling
import numpy as np
from skimage.measure import block_reduce

# Input feature map
input_feature_map = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

# Max Pooling with pool size of (2, 2)
max_pooled_feature_map = block_reduce(input_feature_map, (2, 2), np.max)

print("Input Feature Map:\n", input_feature_map)
print("Max Pooled Feature Map:\n", max_pooled_feature_map)

Input Feature Map:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Max Pooled Feature Map:
 [[ 6  8]
 [14 16]]


In [2]:
# Python code for Average Pooling
import numpy as np
from skimage.measure import block_reduce

# Input feature map
input_feature_map = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

# Average Pooling with pool size of (2, 2)
average_pooled_feature_map = block_reduce(input_feature_map, (2, 2), np.mean)

print("Input Feature Map:\n", input_feature_map)
print("Average Pooled Feature Map:\n", average_pooled_feature_map)

Input Feature Map:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Average Pooled Feature Map:
 [[ 3.5  5.5]
 [11.5 13.5]]


In [3]:
# Python code for Sum Pooling
import numpy as np
from skimage.measure import block_reduce

# Input feature map
input_feature_map = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

# Sum Pooling with pool size of (2, 2)
sum_pooled_feature_map = block_reduce(input_feature_map, (2, 2), np.sum)

print("Input Feature Map:\n", input_feature_map)
print("Sum Pooled Feature Map:\n", sum_pooled_feature_map)

Input Feature Map:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Sum Pooled Feature Map:
 [[14 22]
 [46 54]]


In [4]:
# Python code for CNN with Max Pooling
import tensorflow as tf

model = tf.keras.models.Sequential([
    tf.keras.layers.Conv2D(32, (3,3), activation='relu', input_shape=(28,28,1)),
    tf.keras.layers.MaxPooling2D(2,2),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(10)
])

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 26, 26, 32)        320       
                                                                 
 max_pooling2d (MaxPooling2  (None, 13, 13, 32)        0         
 D)                                                              
                                                                 
 flatten (Flatten)           (None, 5408)              0         
                                                                 
 dense (Dense)               (None, 128)               692352    
                                                                 
 dense_1 (Dense)             (None, 10)                1290      
                                                                 
Total params: 693962 (2.65 MB)
Trainable params: 693962 (2.65 MB)
Non-trainable params: 0 (0.00 Byte)
____________________

In [9]:
# Python code for RNN with Max Pooling
import tensorflow as tf

model = tf.keras.models.Sequential([
    tf.keras.layers.Embedding(input_dim=10000, output_dim=32),
    tf.keras.layers.LSTM(32, return_sequences=True), # Set return_sequences to True
    tf.keras.layers.MaxPooling1D(),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, None, 32)          320000    
                                                                 
 lstm_1 (LSTM)               (None, None, 32)          8320      
                                                                 
 max_pooling1d_3 (MaxPoolin  (None, None, 32)          0         
 g1D)                                                            
                                                                 
 dense_6 (Dense)             (None, None, 1)           33        
                                                                 
Total params: 328353 (1.25 MB)
Trainable params: 328353 (1.25 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [6]:
# Python code for Image Classification with Max Pooling
import tensorflow as tf

model = tf.keras.models.Sequential([
    tf.keras.layers.Conv2D(32, (3,3), activation='relu', input_shape=(28,28,1)),
    tf.keras.layers.MaxPooling2D(2,2),
    tf.keras.layers.Conv2D(64, (3,3), activation='relu'),
    tf.keras.layers.MaxPooling2D(2,2),
    tf.keras.layers.Conv2D(128, (3,3), activation='relu'),
    tf.keras.layers.MaxPooling2D(2,2),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(10)
])

model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_1 (Conv2D)           (None, 26, 26, 32)        320       
                                                                 
 max_pooling2d_1 (MaxPoolin  (None, 13, 13, 32)        0         
 g2D)                                                            
                                                                 
 conv2d_2 (Conv2D)           (None, 11, 11, 64)        18496     
                                                                 
 max_pooling2d_2 (MaxPoolin  (None, 5, 5, 64)          0         
 g2D)                                                            
                                                                 
 conv2d_3 (Conv2D)           (None, 3, 3, 128)         73856     
                                                                 
 max_pooling2d_3 (MaxPoolin  (None, 1, 1, 128)        

In [7]:
# Python code for Text Classification with Max Pooling
import tensorflow as tf

model = tf.keras.models.Sequential([
    tf.keras.layers.Embedding(input_dim=10000, output_dim=32),
    tf.keras.layers.Conv1D(32, 7, activation='relu'),
    tf.keras.layers.MaxPooling1D(),
    tf.keras.layers.Conv1D(64, 5, activation='relu'),
    tf.keras.layers.MaxPooling1D(),
    tf.keras.layers.Conv1D(128, 3, activation='relu'),
    tf.keras.layers.GlobalMaxPooling1D(),
    tf.keras.layers.Dense(1)
])

model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, None, 32)          320000    
                                                                 
 conv1d (Conv1D)             (None, None, 32)          7200      
                                                                 
 max_pooling1d_1 (MaxPoolin  (None, None, 32)          0         
 g1D)                                                            
                                                                 
 conv1d_1 (Conv1D)           (None, None, 64)          10304     
                                                                 
 max_pooling1d_2 (MaxPoolin  (None, None, 64)          0         
 g1D)                                                            
                                                                 
 conv1d_2 (Conv1D)           (None, None, 128)        